;@Ahk2Exe-
#SingleInstance, Force
SetBatchLines, -1
Gui, Add, Text,, File to read:
Gui, Add, Edit, vFilenameRead ym
Gui, Add, Button, default, OK
Gui, Show,, Advanced Encoder
return

GuiClose:
ButtonOK:
Gui, Submit
FileRead, OldStr, %FilenameRead%
NewStr := StrReplace(OldStr, a, "©ª")
NewStr2 := StrReplace(NewStr, b, "¢©")
NewStr := StrReplace(NewStr2, c, "©¢")
NewStr2 := StrReplace(NewStr, d, "ª©")
NewStr := StrReplace(NewStr2, e, "")
NewStr2 := StrReplace(NewStr, f, "")
NewStr := StrReplace(NewStr2, g, "")
NewStr2 := StrReplace(NewStr, h, "")
NewStr := StrReplace(NewStr2, i, "")
NewStr2 := StrReplace(NewStr, j, "")
NewStr := StrReplace(NewStr2, k, "")
NewStr2 := StrReplace(NewStr, l, "")
NewStr := StrReplace(NewStr2, m, "")
NewStr2 := StrReplace(NewStr, n, "")
NewStr := StrReplace(NewStr2, o, "")
NewStr2 := StrReplace(NewStr, p, "")
NewStr := StrReplace(NewStr2, q, "")
NewStr2 := StrReplace(NewStr, r, "")
NewStr := StrReplace(NewStr2, s, "")
NewStr2 := StrReplace(NewStr, t, "")
NewStr := StrReplace(NewStr2, u, "")
NewStr2 := StrReplace(NewStr, v, "")
NewStr := StrReplace(NewStr2, w, "")
NewStr2 := StrReplace(NewStr, x, "")
NewStr := StrReplace(NewStr2, y, "")
NewStr2 := StrReplace(NewStr, z, "")
NewStr := StrReplace(NewStr2, 1, "")
NewStr2 := StrReplace(NewStr, 2, "")
NewStr := StrReplace(NewStr2, 3, "")
NewStr2 := StrReplace(NewStr, 4, "")
NewStr := StrReplace(NewStr2, 5, "")
NewStr2 := StrReplace(NewStr, 6, "")
NewStr := StrReplace(NewStr2, 7, "")
NewStr2 := StrReplace(NewStr, 8, "")
NewStr := StrReplace(NewStr2, 9, "")
NewStr2 := StrReplace(NewStr, 0, "")
NewStr := StrReplace(NewStr2, -, "")
NewStr2 := StrReplace(NewStr, =, "")
NewStr := StrReplace(NewStr2, +, "")
NewStr2 := StrReplace(NewStr, _, "")
NewStr := StrReplace(NewStr2, ), "")
NewStr2 := StrReplace(NewStr, (, "")
NewStr := StrReplace(NewStr2, *, "")
NewStr2 := StrReplace(NewStr, &, "")
NewStr := StrReplace(NewStr2, ^, "")
NewStr2 := StrReplace(NewStr, $, "")
NewStr := StrReplace(NewStr2, #, "")
NewStr2 := StrReplace(NewStr, 2, "")
NewStr := StrReplace(NewStr2, !, "")
NewStr2 := StrReplace(NewStr, `, "")
NewStr := StrReplace(NewStr2, ~, "")
NewStr2 := StrReplace(NewStr, [, "")
NewStr := StrReplace(NewStr2, ], "")
NewStr2 := StrReplace(NewStr, {, "")
NewStr := StrReplace(NewStr2, }, "")
NewStr2 := StrReplace(NewStr, \, "")
NewStr := StrReplace(NewStr2, |, "")
NewStr2 := StrReplace(NewStr, /, "")
NewStr := StrReplace(NewStr2, ?, "")
; Format for converter - NewStr := StrReplace(OldStr, To Be Replaced, "Replace With")
